<?php 
include('assets/inc/top.inc');
include('assets/inc/header.inc');
include('assets/inc/nav.inc');
include("slide/slide.php");
include("assets/inc/main.inc");
include("assets/inc/features.inc");
include("assets/inc/copaci.inc");
include("assets/inc/sociales.inc");
include("assets/inc/interes.inc");
include("assets/inc/footer.inc");
 ?>