<div class="row 200%">
							<div class="12u">

								<!-- Blog -->
									<section class="box blog">
										<h2 class="major"><span>Blog Oficial de Nicolás Romero</span></h2>
										<div>
											<div class="row">
												<div class="9u 12u(mobile)">
													<div class="content content-left">

														<!-- Featured Post -->
															<article class="box post">
																<header>
																	<h3><a href="#">Participar es tu derecho</a></h3>
																	<p>CONVOCATORIA PARA LA ELECCIÓN DE LOS CONSEJOS DE PARTICIPACIÓN CIUDADANA Y DELEGACIONES MUNICIPALES PARA EL PERIODO 2016-2019 </p>
																	<!-- <ul class="meta">
																		<li class="icon fa-clock-o">Posteado hace 15 mins</li>
																		<li class="icon fa-comments"><a href="#">8</a></li>
																	</ul> -->
																</header>
																<a href="convocatoriaCOPACI.php" class="image featured"><img src="images/pic05.png" alt="" /></a>
																<p>
																	Dirigida a todos los vecinos de las Colonias, Fraccionamientos y Pueblos citados en la presente convocatoria en vigor,  que deseen participar en el proceso democrático de la renovación de los Consejos de Participación Ciudadana y Delegaciones de la localidad donde tengan su residencia legal, de acuerdo a las siguientes:

																</p>
																<a href="convocatoriaCOPACI.php" class="button">Participa</a>
															</article>

													</div>
												</div>