						<div class="row 200%">
							<div class="12u">
							<!-- Features -->
									<section class="box features">
										<h2 class="major"><span>100 Días de Trabajo y Resultados</span></h2>
										<div>
											<div class="cuadroDir">
											<div class="cuadroVideo">
												<a href="#">
												 <iframe class="youtube-player" type="text/html" width="420" height="315" src="http://www.youtube.com/embed/Mv7NArqPT8E" allowfullscreen frameborder="0"></iframe>
												</a>
												<h3><a href="#"></a></h3>
											</div>
											<br>


											<div class="cuadroVideo">
												<a href="#">
												 <iframe class="youtube-player" type="text/html" width="420" height="315" src="http://www.youtube.com/embed/hxQ_YXQUJaM" allowfullscreen frameborder="0"></iframe>
												</a>
												<h3><a href="#"></a></h3>
											</div>
											<br>

											
									</section>

							</div>
						</div>