<div class="row 200%">
							<div class="12u">

								<!-- Blog -->
									<section class="box blog">
										<!-- <h2 class="major"><span>Blog Oficial de Nicolás Romero</span></h2> -->
										<div>
											<div class="row">
												<div class="9u 12u(mobile)">
													<div class="content content-left">

														<!-- Featured Post -->
															<article class="box post">
																<header>
																	<h3><a href="#">Convoca</a></h3>
																	<p>A las Empresas e Instituciones educativas privadas ...</p>
																	<!-- <ul class="meta">
																		<li class="icon fa-clock-o">Posteado hace 15 mins</li>
																		<li class="icon fa-comments"><a href="#">8</a></li>
																	</ul> -->
																</header>
																<a href="pdf/CONVOCATORIA_ESR_2017.pdf" class="image featured"><img src="images/banner_convocatoria_2017.png" alt="" /></a>
																<p>
																	A PARTICIPAR EN EL PROCESO DE DIAGNÓSTICO PARA LA OBTENCIÓN DEL DISTINTIVO ESR® 2017, COMO EMPRESA SOCIALMENTE RESPONSABLE.
																	<br>
																	<br>
																	Sobre el Distintivo ESR®
																</p>
																<a href="pdf/CONVOCATORIA_ESR_2017.pdf" class="button">Continuar leyendo..</a>
															</article>

													</div>
												</div>
											</div>
										</div>
									</section>
							</div>
</div>