
</div>
										</div>
									</section>

							</div>
						</div>
					</div>
				</div>
<!-- Footer -->
				<footer id="footer" class="container">
					<!-- <div class="row 200%">
						<div class="12u">

								<section>
									<h2 class="major"><span>Separador</span></h2>
									<p>
										Texto
									</p>
								</section>

						</div>
					</div> -->
					<div class="row 200%">
						<div class="12u">

							<!-- Contact -->
								<section>
									<h2 class="major"><span>Redes sociales</span></h2>
									<ul class="contact">
										<li><a class="icon fa-facebook" href="#"><span class="label">Facebook</span></a></li>
										<li><a class="icon fa-twitter" href="#"><span class="label">Twitter</span></a></li>
										<li><a class="icon fa-instagram" href="#"><span class="label">Instagram</span></a></li>
										<li><a class="icon fa-youtube" href="#"><span class="label">Youtube</span></a></li>
										<!-- <li><a class="icon fa-google-plus" href="#"><span class="label">Google+</span></a></li> -->
									</ul>
								</section>

						</div>
					</div>

					<!-- Copyright -->
						<div id="copyright">
							<ul class="menu">
								<li>&copy; Todos los derechos reservados</li><li>Creado por: <a href="#">H. Ayuntamiento de Nicolás Romero 2016 - 2018</a></li>
								<br>
								<p>Av. Juarez s/n Col. Centro Nicolás Romero, Estado de México C.P. 54400 Tel: 58-71-25-00</p>
							</ul>
						</div>

				</footer>

			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>
			<script type="text/javascript" src="assets/js/jquery.cycle2.js"></script>
</body>
</html>