<div class="row 200%">
							<div class="12u">

								<!-- Blog -->
									<section class="box blog">
										<h2 class="major"><span>Blog Oficial de Nicolás Romero</span></h2>
										<div>
											<div class="row">
												<div class="9u 12u(mobile)">
													<div class="content content-left">

														<!-- Featured Post -->
															<article class="box post">
																<header>
																	<h3><a href="#">Participar es tu derecho</a></h3>
																	<p>Sistema de Capacitación y Certificación para Entrenadores Deportivos</p>
																	<!-- <ul class="meta">
																		<li class="icon fa-clock-o">Posteado hace 15 mins</li>
																		<li class="icon fa-comments"><a href="#">8</a></li>
																	</ul> -->
																</header>
																<a href="pdf/imcufide/Solicitud_InscripcionSC-01.pdf" class="image featured"><img src="images/imcufide.jpg" alt="" /></a>
																<p>
																	18 y 20 de mayo de 11:00 A 18:00 horas calle Clavel s/n Col. Independencia 1ra secc.
																	<br>
																	C.P. 54409 Nicolás Romero, Edo. De Méx.
																	<br>
																	Tel: 5828-5273

																	<br>
																	<br>
																	<b>Requisitos</b>
																	<br>
																	•	Acta de nacimiento
																	<br>
																	•	CURP
																	<br>
																	•	Constancia de Domicilio
																	<br>
																	•	Constancia de Salud (no certificado médico)
																	<br>
																	•	2 Fotos Ovalo Tamaño Credencial b/n mate
																	<br>
																	•	1 Foto tamaño infantil
																	<br>
																	•	Llenado de Solicitud
																	<br>
																	•	Mayores a 16 años
																	<br>
																	•	FM / Residencia
																	<br>
																	•	Manual Electrónico (Libre)

																</p>
																<a href="pdf/imcufide/Solicitud_InscripcionSC-01.pdf" class="button">Participa</a>
															</article>

													</div>
												</div>