<div class="row 200%">
							<div class="12u">

								<!-- Blog -->
										<div>
											<div class="row">
												<div class="9u 12u(mobile)">
													<div class="content content-left">

														<!-- Featured Post -->
															<article class="box post">
																<header>
																	<h3><a href="#">Primer Informe</a></h3>
																	<p>De Trabajo y Resultados</p>
																	<!-- <ul class="meta">
																		<li class="icon fa-clock-o">Posteado hace 15 mins</li>
																		<li class="icon fa-comments"><a href="#">8</a></li>
																	</ul> -->
																</header>
																<a href="https://youtu.be/FX3pAPErc90" class="image featured"><img src="images/banner_1erInformeT.png" alt="" /></a>
																<p>
																	No te pierdas la repetición de transmisión 1er Informe de Trabajo y Resultados!
																	<br>
																</p>
																<a href="https://youtu.be/FX3pAPErc90" class="button">Click aquí para ver</a>
															</article>

													</div>
												</div>