			<!-- Nav -->
				<nav id="nav">
					<ul>
						<li class="current"><a href="index.php">Inicio</a></li>
						<li>
							<a href="#">Ayuntamiento</a>
							<ul>
								<li><a href="mensaje.php">Mensaje de la Presidenta</a></li>
								<li><a href="ayuntaBando.php">Bando Municipal</a></li>
								<li><a href="ayuntaCabildo.php">Cabildo</a></li>
								<li><a href="directorio.php">Directorio</a></li>
								<!-- <li>
									<a href="#">Texto</a>
									<ul>
										<li><a href="#">Texto</a></li>
										<li><a href="#">Texto</a></li>
										<li><a href="#">Texto</a></li>
										<li><a href="#">Texto</a></li>
									</ul>
								</li> -->
								<li><a href="ayuntaOrgani.php">Organigrama</a></li>
								<li>
									<a href="#">Dependencias y Organismos</a>
									<ul>
										<li><a href="#">DIF</a></li>
										<li><a href="#">IMCUFIDE</a></li>
										<li><a href="http://www.sapasnir.mx">SAPASNIR</a></li>
									</ul>
								</li>
							</ul>
						</li>
						<li><a href="tramServ.php">Trámites y Servicios</a>
<!-- 							<ul>
								<li><a href="pdf/tramitesServicios/CARTILLAS.pdf" target="_blank">Cartillas</a></li>
								<li><a href="#" target="_blank">Catastro</a></li>
								<li><a href="#" target="_blank">Constancias</a></li>
								<li><a href="pdf/tramitesServicios/CONTRALORIA.pdf" target="_blank">Contraloría</a></li>
								<li><a href="pdf/tramitesServicios/DESARROLLO_ECONOMICO.pdf" target="_blank">Desarrollo Eco.</a></li>
								<li><a href="pdf/tramitesServicios/DESARROLLO_URBANO.pdf" target="_blank">Desarrollo Urb.</a></li>
								<li><a href="pdf/tramitesServicios/EDUCACION.pdf" target="_blank">Educación</a></li>
								<li><a href="#" target="_blank">IMCUFIDE</a></li>
								<li><a href="pdf/tramitesServicios/MEDIO_AMBIENTE.pdf" target="_blank">Medio Ambiente</a></li>
								<li><a href="pdf/tramitesServicios/NORMATIVIDAD.pdf" target="_blank">Normatividad</a></li>
								<li><a href="pdf/tramitesServicios/OFICIALIA_COMUN_DE_PARTES.pdf" target="_blank">Oficialía Común</a></li>
								<li><a href="#" target="_blank">Predial</a></li>
							</ul> -->
						</li>

						<li><a href="https://www.facebook.com/H.Aytto.NicolasRomero">Noticias</a></li>
<!-- 						<li><a href="http://www.ipomex.org.mx/ipo/portal/nicolasromero.web">Transparencia</a></li> -->
						<li>
							<a href="#">Transparencia</a>
							<ul>
								<li><a href="imco_legFiscal.php">Legislación Fiscal</a></li>
								<li><a href="imco_rendCuentas.php">Rendición de Cuentas</a></li>
								<li><a href="imco_Deuda.php">Deuda</a></li>
								<li><a href="imco_Admin.php">Administración</a></li>
							</ul>
						</li>
					</ul>
				</nav>