			<!-- Nav -->
				<nav id="nav">
					<ul>
						<li class="current"><a href="index.php">Inicio</a></li>
						<li>
							<a href="#">Ayuntamiento</a>
							<ul>
								<li><a href="#">Mensaje de la Presidenta</a></li>
								<li><a href="ayuntaBando.php">Bando Municipal</a></li>
								<li><a href="ayuntaCabildo.php">Cabildo</a></li>
								<!-- <li>
									<a href="#">Texto</a>
									<ul>
										<li><a href="#">Texto</a></li>
										<li><a href="#">Texto</a></li>
										<li><a href="#">Texto</a></li>
										<li><a href="#">Texto</a></li>
									</ul>
								</li> -->
								<li><a href="ayuntaOrgani.php">Organigrama</a></li>
								<li>
									<a href="#">Dependencias y Organismos</a>
									<ul>
										<li><a href="#">DIF</a></li>
										<li><a href="#">IMCUFIDE</a></li>
										<li><a href="#">SAPASNIR</a></li>
									</ul>
								</li>
							</ul>
						</li>
						<li><a href="#">Trámites y Servicios</a>
							<ul>
								<li><a href="#">Bolsa de Trabajo</a></li>
								<li><a href="#">Cartilla Militar</a></li>
								<li><a href="#">Pago de Predial</a></li>
								<li><a href="#">Pago de Agua</a></li>
								<li><a href="#">Registro Civil</a></li>
								<li><a href="#">Servicios Públicos</a></li>
							</ul>
						</li>

						<li><a href="https://www.facebook.com/H.Aytto.NicolasRomero">Noticias</a></li>
						<li><a href="http://www.ipomex.org.mx/ipo/portal/nicolasromero.web">Transparencia</a></li>
					</ul>
				</nav>