						<div class="row 200%">
							<div class="12u">
							<!-- Features -->
									<section class="box features">
									<br>
									<br>
										<h2 class="major"><span>Transmisión en VIVO</span></h2>
										<div>
											<div class="cuadroDir">
											<div class="cuadroVideo">
												<a href="#">
												 <iframe class="youtube-player" type="text/html" src="http://www.youtube.com/embed/Eniv_Y8VMRY" allowfullscreen frameborder="0"></iframe>
												 <!-- <iframe class="youtube-player" type="text/html" width="100%"  src="http://www.youtube.com/embed/12DNBDda6S4" allowfullscreen frameborder="0"></iframe> -->
												</a>
												<h3><a href="#">Inauguración de la Pista de Hielo</a></h3>
											</div>
											<br>
									</section>

							</div>
						</div>