<div class="row 200%">
							<div class="12u">

								<!-- Blog -->
									<section class="box blog">
										<h2 class="major"><span>Blog Oficial de Nicolás Romero</span></h2>
										<div>
											<div class="row">
												<div class="9u 12u(mobile)">
													<div class="content content-left">

														<!-- Featured Post -->
															<article class="box post">
																<header>
																	<h3><a href="#">Inauguración de la Pista de Hielo</a></h3>
																	<p>¡Hoy 9 de Diciembre a las 19:00!</p>
																	<!-- <ul class="meta">
																		<li class="icon fa-clock-o">Posteado hace 15 mins</li>
																		<li class="icon fa-comments"><a href="#">8</a></li>
																	</ul> -->
																</header>
																<a href="https://youtu.be/Eniv_Y8VMRY" class="image featured"><img src="images/pistaHielo.png" alt="" /></a>
																<p>
																	No te pierdas la Transmisión en VIVO
																	<br>
																</p>
																<a href="https://youtu.be/Eniv_Y8VMRY" class="button">Click aquí para ver</a>
															</article>

													</div>
												</div>