<div class="row 200%">
							<div class="12u">

								<!-- Blog -->
									<section class="box blog">
										<!-- <h2 class="major"><span>Blog Oficial de Nicolás Romero</span></h2> -->
										<div>
											<div class="row">
												<div class="9u 12u(mobile)">
													<div class="content content-left">

														<!-- Featured Post -->
															<article class="box post">
																<header>
																	<h3><a href="#">MAGNA JORNADA DE VACUNACIÓN </a></h3>
																	<p>ESTERILIZACIÓN CANINA Y FELINA</p>
																	<!-- <ul class="meta">
																		<li class="icon fa-clock-o">Posteado hace 15 mins</li>
																		<li class="icon fa-comments"><a href="#">8</a></li>
																	</ul> -->
																</header>
																<a href="pdf/vacunacion.pdf" class="image featured"><img src="images/banner_vacunacion.png" alt="" /></a>
																<p>
																	SÁBADO 13 DE AGOSTO DE 8:00 A 14:00HRS. PLAZA ESTADO DE MÉXICO
																	(LERDO DE TEJADA S/N COL. LIBERTAD)
																	<br>
															
																	
																</p>
																<a href="pdf/vacunacion.pdf" class="button">Continuar leyendo..</a>
															</article>

													</div>
												</div>
											</div>
										</div>
									</section>
							</div>
</div>